# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudemux < Formula
  desc "A lazygit-style TUI for managing Claude Code sessions"
  homepage "https://github.com/Merlijnmacgillavry/claudemux"
  version "0.2.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Merlijnmacgillavry/claudemux/releases/download/v0.2.18/claudemux_darwin_amd64.tar.gz"
      sha256 "a27b367ed31dd008223436585f2ced3ada295c73f004c2d72881301cfea700f5"

      define_method(:install) do
        bin.install "claudemux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Merlijnmacgillavry/claudemux/releases/download/v0.2.18/claudemux_darwin_arm64.tar.gz"
      sha256 "fbc93c632469cc894c167fd9c0686d3edebbf38814dcc43e2f25c762a31bb624"

      define_method(:install) do
        bin.install "claudemux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Merlijnmacgillavry/claudemux/releases/download/v0.2.18/claudemux_linux_amd64.tar.gz"
      sha256 "b14e0e8bc686183bc6571f6477c05af43d6d1a69aa6526cf327e6790fce838c5"
      define_method(:install) do
        bin.install "claudemux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Merlijnmacgillavry/claudemux/releases/download/v0.2.18/claudemux_linux_arm64.tar.gz"
      sha256 "d6b5b5295c40a83365aa4f9ac7b4166d73a43bc32985eca7bb8d53ef8481d594"
      define_method(:install) do
        bin.install "claudemux"
      end
    end
  end
end
